### PR TITLE
Bosch imu driver

### PR DESCRIPTION
**Pull request by barbalberto**
yarp driver for bosh IMU BNO055 device.

Tested working!

### CODE REVIEW

**Comment by randaz81** [comment]
I'd move it to yarp, since it's going to be used in non-CER projects too... (e.g. iCub)

**Comment by barbalberto** [comment]
It'll not compile on windows machines and there is no check in cmake files for Win-Linux machine.
I think we have to implement one of the two before moving it to yarp

**Comment by lornat75** [comment]
Why not moving it to yarp? You spare the effort moving it in the future, and there are chances that other people will use it and maybe even make it work on Windows.

**Comment by barbalberto** [comment]
Ok, just updated the cmake and changed namespace from cer::dev to yarp::dev.

It can be moved.

**Comment by barbalberto** [comment]
While moving, can it be renamed to `imuBosch_BNO055`?
To be more similar to 
`imuST_M1`
`imu3DM_GX3`

**Comment by barbalberto** [comment]
Moved!

**Pull request merged**
