### PR TITLE
CER01 and CER02 configuration files configured for flexible motor input.

### PR DESCRIPTION
**Pull request by ale-git**

### CODE REVIEW

**Comment by randaz81** [comment]
Hi @ale-git, I'm going to test these file on CER01 (old prototype).
Can you send me a link to the firmware binaries?

**Comment by ale-git** [comment]
@randaz81 the .hex files are in the devel branch:
icub-firmware-build\testing\mc2plusfmi.hex
icub-firmware-build\testing\mc4plusfmi.hex
icub-firmware-build\testing\ems004fmi.hex

**Comment by ale-git** [comment]
@randaz81 @nunoguedelha the latest commit (back compatible version) is still under debugging. I'll be in IIT on monday btw. Please use version https://github.com/ale-git/icub-main/commit/6cf4ade9be8f2cf05ee2edd6736f22d9cdaeb623 (the same used by Nuno on icub robots) to test the new configuration files. Alternatively, I can test the back compatible version on R1 too.

**Comment by randaz81** [comment]
I did some tests on R1 mk1 (CER01, SN000). 
The branch is not yet ready to be merged, I gave my feedback to @ale-git (some params to be fixed)

**Comment by ale-git** [comment]
@randaz81 I've fixed the parameters that made yarprobotinterface complain in the previous test.

**Comment by marcoaccame** [comment]
@randaz81, @ale-git has already tested the latest commits on R1 and behavior is fine.
Can we can approve the PR or do you need to commit and test any changes?
Thanks, Marco.

**Review by marcoaccame — APPROVED** [review]
after today's meeting, it is OK to approve the PR. cc @ale-git, @randaz81

**Pull request merged**
