### PR TITLE
Add modules for mobile reaching

### PR DESCRIPTION
**Pull request by jchevrie**
This PR adds new functionality for mobile manipulation tasks.
It enables finding an optimal robot base pose and robot joint positions to reach one or several targeted end effector poses.

It adds new modules in the folder `modules/mobile-reaching/` as well as a corresponding new library in `libraries/cer_mobile_kinematics`.
Note that the new library depends on the existing files in `libraries/cer_kinematics/` for the robot kinematics (to avoid duplicates and ease maintainability).

The structure is similar to the `reaching` modules: one `solver`module to solve the optimization problem and one `controller` module to interface with the user and the other navigation modules.
For more details on the modules see `modules/mobile-reaching/README.md`.

Since it is a new functionality, it doesn't break anything already present in this repo.
The only change is the addition of a new configuration name `torso_yaw_no_heave` in  libraries/cer_kinematics.

### CODE REVIEW

**Review by pattacini — COMMENTED** [review]
Hi @jchevrie 

All good 👍 

I've got only one general comment regarding the use of option `torso_yaw_no_heave`. Would it be possible to move it into the new library? Staying at this level would give the impression that this specific modality is available already from within `cer_kinematics`, which is not the case instead.

**Review by pattacini — APPROVED** [review]
Merging and then dealing with this internally.

**Comment by jchevrie** [comment]
Hi @pattacini 
Sorry, I missed your previous comment.

It should be possible to move this change out of 'cer_kinematics' by copy/pasting the file and by modifying the namespaces accordingly.
I just wanted to avoid duplicating too many files and reuse as much as possible to ease maintainability.

I will have a look at it and do the modification if it is not already done.

**Comment by pattacini** [comment]
Hi @jchevrie 👋
Hope you're doing well!
Never mind, everything's already done in https://github.com/robotology/cer/commit/0999a56dc06c297451ecd6b735d24d9c142a34ee.

**Pull request merged**
